services:
  backend_dev:
    container_name: taqseem-backend_dev
    build:
      context: ./backend
      target: dev
    ports:
      - '9000:8000'
    volumes:
      - ./db:/backend/db
      - ./backend/app:/backend/app
    environment:
      STAGE: dev
      DEBUG: True
    profiles:
      - dev
  # frontend_dev:
  #   target:
  #     - dev
  #   build: ./frontend
  #   profiles:
  #     - dev
  backend_test:
    container_name: taqseem-backend_test
    build:
      context: ./backend
      target: prod
    ports:
      - '9001:8000'
    volumes:
      - ./db:/db
    environment:
      STAGE: test
      DEBUG: True
    profiles:
      - test
  # frontend_test:
  #   target:
  #     - dev
  #   build: ./frontend
  #   profiles:
  #    - test
